name: CI

on: push

env:
  DESTDIR: "/tmp/ps5-payload-sdk"
  PS5_PAYLOAD_SDK: "$DESTDIR"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install wget build-essential python3 python3-pyelftools

    - name: Build SDK
      run: make

    - name: Install SDK
      run: make install

    - name: Upload bindist
      uses: actions/upload-artifact@v3
      with:
        path: ${{env.PS5_PAYLOAD_SDK}}
        name: ps5-payload-sdk
  
    - name: Build Samples
      run: |
        make -C samples/hello_world
        make -C samples/klog
        make -C samples/list_files
        make -C samples/pipe_pirate
        make -C samples/ps

