name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo apt update
        sudo apt install bash socat cmake pkg-config clang-15 lld-15

    - name: Build
      run: |
        make
        make DESTDIR=${{ runner.tool_cache }}/ps5-payload-sdk install
        tar -zcf ps5-payload-sdk.tar.gz -C ${{ runner.tool_cache }}/ps5-payload-sdk .

    - name: Test
      run: bash ci.sh

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: SDK
        path: ./ps5-payload-sdk.tar.gz
        if-no-files-found: error

